In [3]:
import pandas as pd

df = pd.read_csv("../data/raw/spotify-2023.csv", encoding="latin1")
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [4]:
df.sample(10)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
141,Novo Balanï¿½,"Veigh, Bvga Beatz, Supernova Ent, Prod Malax",4,2023,5,19,283,7,81102253,6,...,124,D#,Minor,84,65,50,67,0,13,6
244,Until I Found You,Stephen Sanchez,1,2021,9,1,4427,4,726434358,69,...,202,A#,Major,34,25,51,69,0,18,4
12,Flowers,Miley Cyrus,1,2023,1,12,12211,115,1316855716,300,...,118,NaN,Major,71,65,68,6,0,3,7
439,Agudo Mï¿½ï¿½gi,"Styrx, utku INC, Thezth",3,1930,1,1,323,0,90598517,4,...,130,F#,Minor,65,49,80,22,4,7,5
319,Murder In My Mind,Kordhell,1,2022,1,21,2459,20,448843705,20,...,120,A#,Major,71,57,97,1,0,13,11
164,Save Your Tears,The Weeknd,1,2020,3,20,12688,13,1591223784,197,...,118,NaN,Major,68,61,82,2,0,50,3
605,OUT OUT (feat. Charli XCX & Saweetie),"Charli XCX, Jax Jones, Joel Corry, Saweetie",4,2021,8,13,6890,0,427486004,122,...,124,G#,Minor,79,79,84,2,0,5,5
77,Unholy (feat. Kim Petras),"Sam Smith, Kim Petras",2,2022,9,22,8576,42,1230675890,216,...,131,D,Major,71,24,47,1,0,27,9
395,Space Song,Beach House,1,2015,1,1,17852,4,789753877,69,...,147,NaN,Minor,51,62,79,22,13,14,3
525,One Right Now (with The Weeknd),"The Weeknd, Post Malone",2,2021,11,5,4771,0,539595276,68,...,97,C#,Major,68,72,78,4,0,7,5

In [5]:
df.shape

(953, 24)

In [6]:
df.head().style.set_table_styles([
    {"selector": "th", "props": [
        ("background-color", "#1DB954"),
        ("color", "white"),
        ("font-weight", "bold"),
        ("text-align", "center")
    ]}
])

In [7]:
df.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: int64(17), object(7)
memory usage: 178.8+ KB

In [9]:
df.isnull().sum()
df.isnull().sum() / len(df) * 100

track_name              0.00000
artist(s)_name          0.00000
artist_count            0.00000
released_year           0.00000
released_month          0.00000
released_day            0.00000
in_spotify_playlists    0.00000
in_spotify_charts       0.00000
streams                 0.00000
in_apple_playlists      0.00000
in_apple_charts         0.00000
in_deezer_playlists     0.00000
in_deezer_charts        0.00000
in_shazam_charts        5.24659
bpm                     0.00000
key                     9.96852
mode                    0.00000
danceability_%          0.00000
valence_%               0.00000
energy_%                0.00000
acousticness_%          0.00000
instrumentalness_%      0.00000
liveness_%              0.00000
speechiness_%           0.00000
dtype: float64

In [10]:
df.duplicated().sum()

0

In [11]:
df.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,67.812172,51.908709,2.666317,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,86.441493,50.630241,6.035599,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,13.000000,7.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,34.000000,38.000000,0.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,88.000000,87.000000,2.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,672.000000,275.000000,58.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [12]:
pd.to_numeric(df["streams"], errors="coerce").isna().sum()

1

In [13]:
df[pd.to_numeric(df["streams"], errors="coerce").isna()]["streams"]

574    BPM110KeyAModeMajorDanceability53Valence75Ener...
Name: streams, dtype: object

In [14]:
key_mode_counts = (
    df.groupby(["key", "mode"])
      .size()
      .unstack(fill_value=0)
)

In [15]:
df["key"].value_counts()

key
C#    120
G      96
G#     91
F      89
B      81
D      81
A      75
F#     73
E      62
A#     57
D#     33
Name: count, dtype: int64

In [16]:
df["key"].value_counts().head(5)

key
C#    120
G      96
G#     91
F      89
B      81
Name: count, dtype: int64

In [17]:
key_mode_counts = pd.crosstab(df["key"], df["mode"])

key_mode_counts.columns = ["Major", "Minor"]

top_keys = df["key"].value_counts().head(5).index

key_mode_counts = key_mode_counts.loc[top_keys]

key_mode_percent = key_mode_counts.div(
    key_mode_counts.sum(axis=1),
    axis=0
) * 100

In [18]:
print(df["mode"].value_counts())
print()
print(key_mode_counts)
print()
print(key_mode_percent)

mode
Major    550
Minor    403
Name: count, dtype: int64

     Major  Minor
key
C#      73     47
G       66     30
G#      63     28
F       44     45
B       35     46

         Major      Minor
key
C#   60.833333  39.166667
G    68.750000  31.250000
G#   69.230769  30.769231
F    49.438202  50.561798
B    43.209877  56.790123

In [19]:
df["bpm"].value_counts()

bpm
120    39
140    31
130    31
92     25
110    24
       ..
182     1
204     1
192     1
163     1
165     1
Name: count, Length: 124, dtype: int64

In [20]:
(df.sort_values("bpm", ascending=False)[["track_name", "artist(s)_name", "bpm"]].head(10)
   .head(10)
   .style
   .set_table_styles([{"selector": "th", "props": [("background-color", "#1DB954"), ("color", "white")]}])
   .background_gradient(subset=["bpm"], cmap="Greens")
)

In [21]:
print("Mean:", round(df["bpm"].mean(), 2), "BPM")
print("Median:", round(df["bpm"].median(), 2), "BPM")

Mean: 122.54 BPM
Median: 121.0 BPM

### Tempo

Das durchschnittliche Tempo der Songs liegt bei **122,54 BPM**, während der Median bei **121 BPM** liegt. Die geringe Differenz von 1,54 BPM deutet darauf hin, dass extreme BPM-Werte den Mittelwert nur geringfügig beeinflussen.

Der Median beschreibt damit das typische Tempo des Datensatzes robuster gegenüber Ausreißern und liegt bei **121 BPM**.