In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/processed/spotify-2023-cleaned.csv", encoding="utf-8")

In [2]:
top_5_streams = (
    df[["track_name", "artist(s)_name", "streams"]]
    .sort_values("streams", ascending=False)
    .head(5)
)

top_5_streams

,track_name,artist(s)_name,streams
55,Blinding Lights,The Weeknd,3.703895e+09
179,Shape of You,Ed Sheeran,3.562544e+09
86,Someone You Loved,Lewis Capaldi,2.887242e+09
617,Dance Monkey,Tones and I,2.864792e+09
41,Sunflower - Spider-Man: Into the Spider-Verse,"Post Malone, Swae Lee",2.808097e+09

In [3]:
top_5_streams_year = (
    df[
        [
            "track_name",
            "artist(s)_name",
            "streams",
            "released_year"
        ]
    ]
    .sort_values("streams", ascending=False)
    .head(5)
)

top_5_streams_year

,track_name,artist(s)_name,streams,released_year
55,Blinding Lights,The Weeknd,3.703895e+09,2019
179,Shape of You,Ed Sheeran,3.562544e+09,2017
86,Someone You Loved,Lewis Capaldi,2.887242e+09,2018
617,Dance Monkey,Tones and I,2.864792e+09,2019
41,Sunflower - Spider-Man: Into the Spider-Verse,"Post Malone, Swae Lee",2.808097e+09,2018

In [4]:
top_5_streams_year = top_5_streams_year.copy()
top_5_streams_year["song_age"] = 2023 - top_5_streams_year["released_year"]

top_5_streams_year

,track_name,artist(s)_name,streams,released_year,song_age
55,Blinding Lights,The Weeknd,3.703895e+09,2019,4
179,Shape of You,Ed Sheeran,3.562544e+09,2017,6
86,Someone You Loved,Lewis Capaldi,2.887242e+09,2018,5
617,Dance Monkey,Tones and I,2.864792e+09,2019,4
41,Sunflower - Spider-Man: Into the Spider-Verse,"Post Malone, Swae Lee",2.808097e+09,2018,5

In [5]:
df.loc[df["key"] != "Unknown", "key"].value_counts().head(5)

key
C#    119
G      96
G#     91
F      89
B      81
Name: count, dtype: int64

In [6]:
df.loc[df["key"] != "Unknown", "key"].value_counts(normalize=True).head(5) * 100

key
C#    13.918129
G     11.228070
G#    10.643275
F     10.409357
B      9.473684
Name: proportion, dtype: float64

In [7]:
# Top 5 Keys insgesamt
top_keys = df.loc[df["key"] != "Unknown", "key"].value_counts().head(5).index

# Major/Minor-Verteilung
key_mode_counts = pd.crosstab(
    df.loc[df["key"] != "Unknown", "key"],
    df["mode"]
)

# Nur Top 5 Keys
key_mode_counts = key_mode_counts.loc[top_keys]

# Prozentwerte innerhalb jedes Keys
key_mode_percent = (
    key_mode_counts
    .div(key_mode_counts.sum(axis=1), axis=0)
    .mul(100)
)

print(key_mode_counts)
print()
print(key_mode_percent.round(1))

mode  Major  Minor
key
C#       72     47
G        66     30
G#       63     28
F        44     45
B        35     46

mode  Major  Minor
key
C#     60.5   39.5
G      68.8   31.2
G#     69.2   30.8
F      49.4   50.6
B      43.2   56.8

Danceability describes how suitable a track is for dancing based on its musical characteristics, particularly rhythm, beat strength and tempo. The value ranges from 0 to 100 in this dataset, with higher values indicating greater danceability.

In [8]:
top_10_danceability = (
    df[["track_name", "artist(s)_name", "danceability_%"]]
    .sort_values("danceability_%", ascending=False)
    .head(10)
)

top_10_danceability

,track_name,artist(s)_name,danceability_%
592,Peru,"Ed Sheeran, Fireboy DML",96
872,Ai Preto,"L7nnon, DJ Biel do Furduncinho, Bianca",95
224,Players,Coi Leray,95
321,CAIRO,"Karol G, Ovy On The Drums",95
422,Super Freaky Girl,Nicki Minaj,95
250,The Real Slim Shady,Eminem,95
699,Starlight,Dave,95
268,Slut Me Out,NLE Choppa,94
142,"Gol Bolinha, Gol Quadrado 2","Mc Pedrinho, DJ 900",93
746,sentaDONA (Remix) s2,"Lu�sa Sonza, MC Frog, Dj Gabriel do Borel, Davi K",93

In [9]:
last_10_danceability = (
    df[["track_name", "artist(s)_name", "danceability_%"]]
    .sort_values("danceability_%", ascending=False)
    .tail(10)
)

last_10_danceability

,track_name,artist(s)_name,danceability_%
683,Still Don't Know My Name,Labrinth,31
659,Notion,The Rare Occasions,31
528,Happier Than Ever,Billie Eilish,31
530,traitor,"Juan Cruz Toledo, Huilen Toledo",29
701,"I'm Tired - From ""Euphoria"" An Original HBO Se...",Labrinth,28
520,Starry Eyes,The Weeknd,28
518,Dawn FM,The Weeknd,27
386,Lift Me Up - From Black Panther: Wakanda Forev...,Rihanna,25
446,It's the Most Wonderful Time of the Year,Andy Williams,24
468,White Christmas,"Bing Crosby, John Scott Trotter & His Orchestr...",23

In [10]:
df["danceability_%"].agg(["mean", "median"])

mean      66.956797
median    69.000000
Name: danceability_%, dtype: float64

In [11]:
top_10_valence = (
    df[["track_name", "artist(s)_name", "valence_%"]]
    .sort_values("valence_%", ascending=False)
    .head(10)
)

top_10_valence

,track_name,artist(s)_name,valence_%
417,Doja,Central Cee,97
892,JGL,"Luis R Conriquez, La Adictiva",97
751,There's Nothing Holdin' Me Back,Shawn Mendes,97
858,En El Radio Un Cochinero,Victor Cibrian,97
359,Zona De Perigo,Leo Santana,97
450,Feliz Navidad,Jos� Felic,96
597,I WANNA BE YOUR SLAVE,M�ne,96
137,"Tere Vaaste (From ""Zara Hatke Zara Bachke"")","Sachin-Jigar, Shadab Faridi, Altamash Faridi, ...",96
25,SABOR FRESA,Fuerza Regida,96
251,MERCHO,"Migrantes, LiL CaKe, Nico Valdi",96

In [12]:
last_10_valence = (
    df[["track_name", "artist(s)_name", "valence_%"]]
    .sort_values("valence_%", ascending=True)
    .head(10)
)

last_10_valence

,track_name,artist(s)_name,valence_%
910,Selfish,PnB Rock,4
667,Down Under (feat. Colin Hay),"Luude, Colin Hay",4
407,After Dark,Mr.Kitty,4
485,Maroon,Taylor Swift,4
242,Just Wanna Rock,Lil Uzi Vert,4
208,Self Love (Spider-Man: Across the Spider-Verse...,"Metro Boomin, Coi Leray",5
862,Massive,Drake,5
747,Falling,Harry Styles,6
419,Rumble,"Skrillex, Flowdan, Fred again..",6
296,Lose Yourself - Soundtrack Version,Eminem,6

In [13]:
top_10_energy = (
    df[["track_name", "artist(s)_name", "energy_%"]]
    .sort_values("energy_%", ascending=False)
    .head(10)
)

top_10_energy

,track_name,artist(s)_name,energy_%
42,I'm Good (Blue),"Bebe Rexha, David Guetta",97
319,Murder In My Mind,Kordhell,97
792,That That (prod. & feat. SUGA of BTS),"PSY, Suga",96
60,T�,"dennis, MC Kevin o Chris",96
367,Bombonzinho - Ao Vivo,"Israel & Rodolffo, Ana Castela",95
474,Merry Christmas,"Ed Sheeran, Elton John",94
174,�,YOASOBI,94
352,Hype Boy,NewJeans,94
576,Freaks,Surf Curse,94
549,Every Angel is Terrifying,The Weeknd,94

In [14]:
last_10_energy = (
    df[["track_name", "artist(s)_name", "energy_%"]]
    .sort_values("energy_%", ascending=True)
    .head(10)
)

last_10_energy

,track_name,artist(s)_name,energy_%
17,What Was I Made For? [From The Motion Picture ...,Billie Eilish,9
326,Heart To Heart,Mac DeMarco,14
459,The Christmas Song (Merry Christmas To You) - ...,Nat King Cole,15
936,Sweet Nothing,Taylor Swift,16
855,Boyfriends,Harry Styles,20
701,"I'm Tired - From ""Euphoria"" An Original HBO Se...",Labrinth,20
694,Something In The Way - Remastered 2021,Nirvana,20
463,Special,SZA,20
444,It's Beginning To Look A Lot Like Christmas,Michael Bubl�,23
945,Bigger Than The Whole Sky,Taylor Swift,24