In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/processed/spotify-2023-cleaned.csv", encoding="latin-1")

In [2]:
top_5_streams = (
    df[["track_name", "artist(s)_name", "streams"]]
    .sort_values("streams", ascending=False)
    .head(5)
)

top_5_streams

,track_name,artist(s)_name,streams
574,Love Grows (Where My Rosemary Goes),Edison Lighthouse,BPM110KeyAModeMajorDanceability53Valence75Ener...
33,Anti-Hero,Taylor Swift,999748277
625,Arcade,Duncan Laurence,991336132
253,Glimpse of Us,Joji,988515741
455,Seek & Destroy,SZA,98709329

In [3]:
top_5_streams_year = (
    df[
        [
            "track_name",
            "artist(s)_name",
            "streams",
            "released_year"
        ]
    ]
    .sort_values("streams", ascending=False)
    .head(5)
)

top_5_streams_year

,track_name,artist(s)_name,streams,released_year
574,Love Grows (Where My Rosemary Goes),Edison Lighthouse,BPM110KeyAModeMajorDanceability53Valence75Ener...,1970
33,Anti-Hero,Taylor Swift,999748277,2022
625,Arcade,Duncan Laurence,991336132,2019
253,Glimpse of Us,Joji,988515741,2022
455,Seek & Destroy,SZA,98709329,2022

In [4]:
top_5_streams_year["song_age"] = 2023 - top_5_streams_year["released_year"]

top_5_streams_year

,track_name,artist(s)_name,streams,released_year,song_age
574,Love Grows (Where My Rosemary Goes),Edison Lighthouse,BPM110KeyAModeMajorDanceability53Valence75Ener...,1970,53
33,Anti-Hero,Taylor Swift,999748277,2022,1
625,Arcade,Duncan Laurence,991336132,2019,4
253,Glimpse of Us,Joji,988515741,2022,1
455,Seek & Destroy,SZA,98709329,2022,1

In [5]:
df["key"].value_counts().head(5)

key
C#    120
G      96
G#     91
F      89
B      81
Name: count, dtype: int64

In [6]:
df["key"].value_counts(normalize=True).head(5) * 100

key
C#    13.986014
G     11.188811
G#    10.606061
F     10.372960
B      9.440559
Name: proportion, dtype: float64

In [7]:
# Top 5 Keys insgesamt
top_keys = df["key"].value_counts().head(5).index

# Major/Minor-Verteilung
key_mode_counts = pd.crosstab(
    df["key"],
    df["mode"]
)

# Mode umbenennen
key_mode_counts = key_mode_counts.rename(
    columns={0: "Minor", 1: "Major"}
)

# Nur Top 5 Keys
key_mode_counts = key_mode_counts.loc[top_keys]

# Prozentwerte innerhalb jedes Keys
key_mode_percent = (
    key_mode_counts
    .div(key_mode_counts.sum(axis=1), axis=0)
    .mul(100)
)

print(key_mode_counts)
print()
print(key_mode_percent.round(1))

mode  Major  Minor
key
C#       73     47
G        66     30
G#       63     28
F        44     45
B        35     46

mode  Major  Minor
key
C#     60.8   39.2
G      68.8   31.2
G#     69.2   30.8
F      49.4   50.6
B      43.2   56.8

Danceability describes how suitable a track is for dancing based on its musical characteristics, particularly rhythm, beat strength and tempo. The value ranges from 0 to 100 in this dataset, with higher values indicating greater danceability.

In [9]:
top_10_danceability = (
    df[["track_name", "artist(s)_name", "danceability_%"]]
    .sort_values("danceability_%", ascending=False)
    .head(10)
)

top_10_danceability

,track_name,artist(s)_name,danceability_%
595,Peru,"Ed Sheeran, Fireboy DML",96
224,Players,Coi Leray,95
250,The Real Slim Shady,Eminem,95
423,Super Freaky Girl,Nicki Minaj,95
702,Starlight,Dave,95
321,CAIRO,"Karol G, Ovy On The Drums",95
876,Ai Preto,"L7nnon, DJ Biel do Furduncinho, Bianca",95
268,Slut Me Out,NLE Choppa,94
943,Privileged Rappers,"Drake, 21 Savage",93
142,"Gol Bolinha, Gol Quadrado 2","Mc Pedrinho, DJ 900",93

In [10]:
last_10_danceability = (
    df[["track_name", "artist(s)_name", "danceability_%"]]
    .sort_values("danceability_%", ascending=False)
    .tail(10)
)

last_10_danceability

,track_name,artist(s)_name,danceability_%
686,Still Don't Know My Name,Labrinth,31
662,Notion,The Rare Occasions,31
531,Happier Than Ever,Billie Eilish,31
533,traitor,"Juan Cruz Toledo, Huilen Toledo",29
704,"I'm Tired - From ""Euphoria"" An Original HBO Se...",Labrinth,28
523,Starry Eyes,The Weeknd,28
521,Dawn FM,The Weeknd,27
387,Lift Me Up - From Black Panther: Wakanda Forev...,Rihanna,25
447,It's the Most Wonderful Time of the Year,Andy Williams,24
469,White Christmas,"Bing Crosby, John Scott Trotter & His Orchestr...",23

In [11]:
df["danceability_%"].agg(["mean", "median"])

mean      66.96957
median    69.00000
Name: danceability_%, dtype: float64

In [12]:
top_10_valence = (
    df[["track_name", "artist(s)_name", "valence_%"]]
    .sort_values("valence_%", ascending=False)
    .head(10)
)

top_10_valence

                          track_name                 artist(s)_name  valence_%
754  There's Nothing Holdin' Me Back                   Shawn Mendes         97
861         En El Radio Un Cochinero                 Victor Cibrian         97
896                              JGL  Luis R Conriquez, La Adictiva         97
418                             Doja                    Central Cee         97
359                   Zona De Perigo                    Leo Santana         97
25                       SABOR FRESA                  Fuerza Regida         96
483  Deck The Hall - Remastered 1999                  Nat King Cole         96
451                    Feliz Navidad                Josï¿½ï¿½ Felic         96
149           El Gordo Trae El Mando                    Chino Pacas         96
117                         Rara Vez                   Taiu, Milo j         96

In [13]:
last_10_valence = (
    df[["track_name", "artist(s)_name", "valence_%"]]
    .sort_values("valence_%", ascending=True)
    .head(10)
)

last_10_valence

,track_name,artist(s)_name,valence_%
487,Maroon,Taylor Swift,4
914,Selfish,PnB Rock,4
242,Just Wanna Rock,Lil Uzi Vert,4
408,After Dark,Mr.Kitty,4
670,Down Under (feat. Colin Hay),"Luude, Colin Hay",4
865,Massive,Drake,5
208,Self Love (Spider-Man: Across the Spider-Verse...,"Metro Boomin, Coi Leray",5
420,Rumble,"Skrillex, Flowdan, Fred again..",6
750,Falling,Harry Styles,6
296,Lose Yourself - Soundtrack Version,Eminem,6

In [14]:
top_10_energy = (
    df[["track_name", "artist(s)_name", "energy_%"]]
    .sort_values("energy_%", ascending=False)
    .head(10)
)

top_10_energy

,track_name,artist(s)_name,energy_%
42,I'm Good (Blue),"Bebe Rexha, David Guetta",97
319,Murder In My Mind,Kordhell,97
795,That That (prod. & feat. SUGA of BTS),"PSY, Suga",96
60,Tï¿½ï¿,"dennis, MC Kevin o Chris",96
367,Bombonzinho - Ao Vivo,"Israel & Rodolffo, Ana Castela",95
475,Merry Christmas,"Ed Sheeran, Elton John",94
552,Every Angel is Terrifying,The Weeknd,94
174,ýýýýýýýýýýýý,YOASOBI,94
430,KICK BACK,Kenshi Yonezu,94
579,Freaks,Surf Curse,94

In [15]:
last_10_energy = (
    df[["track_name", "artist(s)_name", "energy_%"]]
    .sort_values("energy_%", ascending=True)
    .head(10)
)

last_10_energy

,track_name,artist(s)_name,energy_%
17,What Was I Made For? [From The Motion Picture ...,Billie Eilish,9
326,Heart To Heart,Mac DeMarco,14
460,The Christmas Song (Merry Christmas To You) - ...,Nat King Cole,15
940,Sweet Nothing,Taylor Swift,16
858,Boyfriends,Harry Styles,20
464,Special,SZA,20
704,"I'm Tired - From ""Euphoria"" An Original HBO Se...",Labrinth,20
697,Something In The Way - Remastered 2021,Nirvana,20
445,It's Beginning To Look A Lot Like Christmas,Michael Bublï¿,23
949,Bigger Than The Whole Sky,Taylor Swift,24